/**
 *  Static setup unstructured Text Corpus (Vulnerability Advisories and General Guidance)
 *
 * (c) 2025 Maksim Avilov, mavilov@hotmail.com
 */

//TODO: maybe load from external files instead of hardcoding here or crawl https://security.snyk.io/vuln/ etc.
export const CORPUS = [
    'A detailed advisory for CVE-2024-001 affecting Node.js packages: The issue is a Cross-Site Scripting (XSS) vulnerability found in version 5.0.0-beta.2, which allows remote attackers to inject arbitrary web script or HTML via specific headers. Users should upgrade to 5.1.0 immediately.',
    'High severity vulnerability in Lodash (Prototype Pollution advisory): Affects versions up to 4.17.20. This allows an attacker to add or modify properties of the Object prototype, potentially leading to denial-of-service or remote code execution. Mitigation requires updating to 4.17.21 or later.',
    'Maven security best practices: Always verify package checksums and use dependency management tools that check against public vulnerability databases. Avoid using SNAPSHOT versions in production environments.',
    'A common vulnerability type is Open Redirect (CWE-601), where a web application allows a user to control a destination URL, potentially tricking them into visiting a malicious site. Patches often involve strict whitelisting of redirect targets.',
    'The current policy for vulnerability response is a 72-hour turnaround time for patch deployment after a CVE is publicly disclosed for critical severity issues.',
    'The Jackson-databind package had multiple deserialization flaws (CVE-2023-9999) impacting version 2.15.0 and earlier. The fix involves blacklisting known gadgets and using secure deserialization configurations.',
    'There is a Medium severity vulnerability in Express.js (CVE-2024-002) that allows for HTTP Parameter Pollution (HPP) attacks. This can lead to unexpected behavior in applications. Users should upgrade to version 4.18.2 or later. Express.js is often referred as express and it is available as npm package.',
    'General advice for maintaining secure software dependencies includes regularly auditing your dependency tree, using tools like Snyk or Dependabot, and subscribing to security mailing lists relevant to your tech stack.',
    'Critical vulnerabilities should be prioritized based on their CVSS scores, exploitability, and the presence of active exploits in the wild. A risk-based approach ensures that resources are allocated effectively to mitigate the most pressing threats.',
    "For Python packages, it's essential to avoid using packages with known vulnerabilities listed in the PyPI advisory database. Always check the package's issue tracker and changelog for recent security fixes before integrating it into your project.",
    'Apache Log4j2 2.0-beta9 through 2.15.0 (excluding security releases 2.12.2, 2.12.3, and 2.3.1) JNDI features used in configuration, log messages, and parameters do not protect against attacker controlled LDAP and other JNDI related endpoints. An attacker who can control log messages or log message parameters can execute arbitrary code loaded from LDAP servers when message lookup substitution is enabled. From log4j 2.15.0, this behavior has been disabled by default. From version 2.16.0 (along with 2.12.2, 2.12.3, and 2.3.1), this functionality has been completely removed. Note that this vulnerability is specific to log4j-core and does not affect log4net, log4cxx, or other Apache Logging Services projects.',
    'axios is a promise-based HTTP client for the browser and Node.js. Affected versions of this package are vulnerable to Allocation of Resources Without Limits or Throttling via the data: URL handler. An attacker can trigger a denial of service by crafting a data: URL with an excessive payload, causing allocation of memory for content decoding before verifying content size limits.',
    'Axios v1.10.0 introduces a critical vulnerability via its transitive dependency on form-data@4.0.0. According to Snyk Security Advisory SNYK-JS-FORMDATA-10841150, this version of form-data is affected by a Predictable Value Range from Previous Values issue, which can lead to HTTP parameter pollution and potentially allow boundary manipulation in multipart requests. Expected behavior: Axios should avoid depending on a vulnerable version of form-data. The expected behavior is that form-data@4.0.4 or higher is used to prevent exposure to known critical vulnerabilities.',
    'Predictable Value Range from Previous Values. Affecting form-data package, versions <2.5.4>=3.0.0 <3.0.4>=4.0.0 <4.0.4. INTRODUCED: 18 JUL 2025 CVE-2025-7783 CWE-343 How to fix? Upgrade form-data to version 2.5.4, 3.0.4, 4.0.4 or higher. Overview. Affected versions of this package are vulnerable to Predictable Value Range from Previous Values via the boundary value, which uses Math.random(). An attacker can manipulate HTTP request boundaries by exploiting predictable values, potentially leading to HTTP parameter pollution. Snyk ID SNYK-JS-FORMDATA-10841150, Published 20 Jul 2025, Disclosed 18 Jul 2025, Credit: Ben Shonaldmann',
    'Malicious Package. Severity: CRITICAL. Affecting validator-node package, versions *. INTRODUCED: 14 NOV 2025. How to fix? Avoid using all malicious instances of the validator-node package. Overview. Validator-node is a malicious package. This package contains malicious code, and its content was removed from the official package manager. While this package might be attempting to impersonate a valid organization, there is no connection between that organization and this package authorship. Snyk ID: SNYK-JS-VALIDATORNODE-13961690. Published 14 Nov 2025, Disclosed 14 Nov 2025.',
    'hybrid-query-system is a GitHub project in private repository that combines traditional keyword-based search with vector-based semantic search to enhance information retrieval. It leverages TF-IDF for keyword matching and advanced embedding models for capturing semantic meaning, providing a comprehensive search experience across various data types. It is not available as a package and meant to be run in controlled environments. There are no publicly known vulnerabilities associated with hybrid-query-system as of now. Author Maksim Avilov, first presented on the 18th of November 2025.',
]
